In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [32]:
df=pd.read_csv('StudentsPerformance.csv')

In [33]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [35]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [36]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [37]:
df['gender']=df['gender'].map({'male':0,'female':1})

In [38]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,1,group B,bachelor's degree,standard,none,72,72,74
1,1,group C,some college,standard,completed,69,90,88
2,1,group B,master's degree,standard,none,90,95,93
3,0,group A,associate's degree,free/reduced,none,47,57,44
4,0,group C,some college,standard,none,76,78,75

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
encoder=OneHotEncoder()

In [41]:
encoded=encoder.fit_transform(df[['race/ethnicity']])

In [42]:
encoded_df=pd.DataFrame(
    encoded.toarray(),
    columns=encoder.get_feature_names_out(['race/ethnicity'])
)

In [43]:
df=pd.concat([df,encoded_df],axis=1)

In [44]:
df.drop('race/ethnicity', axis=1, inplace=True)

In [45]:
df.head()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E
0,1,bachelor's degree,standard,none,72,72,74,0.0,1.0,0.0,0.0,0.0
1,1,some college,standard,completed,69,90,88,0.0,0.0,1.0,0.0,0.0
2,1,master's degree,standard,none,90,95,93,0.0,1.0,0.0,0.0,0.0
3,0,associate's degree,free/reduced,none,47,57,44,1.0,0.0,0.0,0.0,0.0
4,0,some college,standard,none,76,78,75,0.0,0.0,1.0,0.0,0.0

In [47]:
df['parental level of education'].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [49]:
# Create ranking dictionary
education_order = {
    'some high school': 0,
    'high school': 1,
    'some college': 2,
    "associate's degree": 3,
    "bachelor's degree": 4,
    "master's degree": 5
}

# Replace text with numerical ranking
df['parental level of education'] = df['parental level of education'].map(education_order)

In [50]:
df.head()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E
0,1,4,standard,none,72,72,74,0.0,1.0,0.0,0.0,0.0
1,1,2,standard,completed,69,90,88,0.0,0.0,1.0,0.0,0.0
2,1,5,standard,none,90,95,93,0.0,1.0,0.0,0.0,0.0
3,0,3,free/reduced,none,47,57,44,1.0,0.0,0.0,0.0,0.0
4,0,2,standard,none,76,78,75,0.0,0.0,1.0,0.0,0.0

In [51]:
df['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

In [52]:
df['lunch']=df['lunch'].map({'standard':0,'free/reduced':1})

In [53]:
df.head()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E
0,1,4,0,none,72,72,74,0.0,1.0,0.0,0.0,0.0
1,1,2,0,completed,69,90,88,0.0,0.0,1.0,0.0,0.0
2,1,5,0,none,90,95,93,0.0,1.0,0.0,0.0,0.0
3,0,3,0,none,47,57,44,1.0,0.0,0.0,0.0,0.0
4,0,2,0,none,76,78,75,0.0,0.0,1.0,0.0,0.0

In [54]:
df['lunch'].unique()

array([0])

In [55]:
df['lunch'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: lunch
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [56]:
df['parental level of education'].isnull().sum()

np.int64(0)

In [58]:
df['test preparation course'].unique()

array(['none', 'completed'], dtype=object)

In [59]:
df['test preparation course']=df['test preparation course'].map({'none':0,'completed':1})

In [60]:
df.head()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E
0,1,4,0,0,72,72,74,0.0,1.0,0.0,0.0,0.0
1,1,2,0,1,69,90,88,0.0,0.0,1.0,0.0,0.0
2,1,5,0,0,90,95,93,0.0,1.0,0.0,0.0,0.0
3,0,3,0,0,47,57,44,1.0,0.0,0.0,0.0,0.0
4,0,2,0,0,76,78,75,0.0,0.0,1.0,0.0,0.0

In [61]:
df['test preparation course'].isnull().sum()

np.int64(0)

In [64]:
X=df.drop('math score',axis=1)
y=df['math score']

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [66]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [67]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [68]:
lr=LinearRegression()
ridge=Ridge()
lasso=Lasso()

In [70]:
lr.fit(X_train,y_train)
ridge.fit(X_train,y_train)
lasso.fit(X_train,y_train)

Lasso()

In [71]:
lr_pred = lr.predict(X_test)
ridge_pred = ridge.predict(X_test)
lasso_pred = lasso.predict(X_test)

In [72]:
print("Linear Regression")
print("R2 Score:", r2_score(y_test, lr_pred))
print("MAE:", mean_absolute_error(y_test, lr_pred))
print("MSE:", mean_squared_error(y_test, lr_pred))

Linear Regression
R2 Score: 0.8792957846950328
MAE: 4.24811553068942
MSE: 29.371970625566245

In [73]:
print("Ridge")
print("R2 Score:", r2_score(y_test, ridge_pred))
print("MAE:", mean_absolute_error(y_test, ridge_pred))
print("MSE:", mean_squared_error(y_test, ridge_pred))

Ridge
R2 Score: 0.8796130392038937
MAE: 4.241487915662452
MSE: 29.294770420987234

In [74]:
print("Lasso")
print("R2 Score:", r2_score(y_test, lasso_pred))
print("MAE:", mean_absolute_error(y_test, lasso_pred))
print("MSE:", mean_squared_error(y_test, lasso_pred))

Lasso
R2 Score: 0.849808236273371
MAE: 4.711955116450633
MSE: 36.54742347841594

In [76]:
import pickle

pickle.dump(ridge, open('model.pkl', 'wb'))

In [77]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [78]:
import os
os.listdir()

['.config',
 'scaler.pkl',
 'model.pkl',
 'StudentsPerformance.csv',
 'sample_data']